# Generated by Django 5.1.2 on 2025-03-29 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_learning_logs', '0005_uploadedbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='new_learning_logs.uploadedbook'),
        ),
    ]
